
# Spring Boot configuration for the "dev" profile.

logging:
  level:
    ROOT: DEBUG
    vdehorta: DEBUG

spring:
  data:
    mongodb:
      database: skispasse-dev
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true
server:
  port: 8080


# Skispasse Application specific properties

application:
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
