
# Spring Boot root configuration file.

spring:
  application:
    name: skispasse
  data:
    mongodb:
      uri: mongodb://localhost:27017
  jmx:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  mvc:
    favicon:
      enabled: false
  output:
    ansi:
      console-available: true
  servlet:
    multipart:
      max-file-size: 2MB
  thymeleaf:
    enabled: false
    check-template-location: false

server:
  servlet:
    session:
      cookie:
        http-only: true


# Skispasse Application specific properties

application:
  application-name: skispasseApp
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
  mongo:
    grid-fs:
      newsfact-video-bucket: newsFactVideo

