# ===================================================================
# Spring Boot configuration.
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  application:
    name: skispasse
  jmx:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  mvc:
    favicon:
      enabled: false
  output:
    ansi:
      console-available: true

  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: #spring.profiles.active#
  servlet:
    multipart:
      max-file-size: 2MB
  thymeleaf:
    enabled: false
    check-template-location: false

server:
  servlet:
    session:
      cookie:
        http-only: true


# ===================================================================
# Skispasse Application specific properties
# ===================================================================

application:
  client-app-name: skispasseApp
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512

