# ===================================================================
# Spring Boot configuration for the "dev" profile.
# This configuration overrides the application.yml file.
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    vdehorta: DEBUG

spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: skispasse
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true
server:
  port: 8080


# ===================================================================
# Skispasse Application specific properties
# ===================================================================

application:
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
  mongo:
    grid-fs:
      newsfact-video-bucket: newsFactVideo
