# ===================================================================
# Spring Boot configuration.
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  application:
    name: skispasse
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: #spring.profiles.active#
  jmx:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  mvc:
    favicon:
      enabled: false
  output:
    ansi:
      console-available: true

server:
  servlet:
    session:
      cookie:
        http-only: true


# ===================================================================
# Skispasse Application specific properties
# ===================================================================

skispasse:
  clientApp:
    name: 'skispasseApp'


